---
name: Test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.7, 3.8, '3.10']
        architecture: ['x64']
        include:
          - os: macos-10.15
            python-version: 3.9
            architecture: 'x64'
          - os: macos-latest
            python-version: 3.9
            architecture: 'x64'
          - name: Windows
            os: windows-latest
            python-version: 3.9
            architecture: 'x64'
          - name: Windows 32-bit
            os: windows-latest
            python-version: 3.9
            architecture: 'x86'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Qt dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
          libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 \
          libxcb-xfixes0 libgl1-mesa-glx libegl1-mesa libfontconfig1 libglib2.0

      - run: pip install PyQt5 PySide2
      - run: pip install PyQt6 PySide6
        if: ${{ matrix.architecture != 'x86'}}

      # In order for Qt to run without a screen, we need to enable Qt's
      # headless mode. .
      - run: echo 'QT_QPA_PLATFORM=offscreen' >> $GITHUB_ENV
        if: startsWith(matrix.os, 'ubuntu')

      - run: bash ./setup-environment.sh

      - run: pytest
        env:
          QT_VARIANT: pyqt5

      - run: pytest
        if: ${{ matrix.architecture != 'x86'}}
        env:
          QT_VARIANT: pyqt6

      - run: pytest
        env:
          QT_VARIANT: pyside2

      - run: pytest
        if: ${{ matrix.architecture != 'x86'}}
        env:
          QT_VARIANT: pyside6

      - run: pip install "pyinstaller @ git+https://github.com/pyinstaller/pyinstaller.git@v4"
      - run: pyinstaller frozen-pytest.spec
        working-directory: tests/PyInstaller_
      - run: ./dist/frozen-pytest/frozen-pytest ../..
        working-directory: tests/PyInstaller_
