---
name: Test

on:
  push:

env:
  FORCE_COLOR: 1

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.8, '3.10']
        architecture: ['x64']
        include:
          - os: macos-10.15
            python-version: 3.9
            architecture: 'x64'
          - os: macos-latest
            python-version: 3.9
            architecture: 'x64'
          - name: Windows
            os: windows-latest
            python-version: 3.9
            architecture: 'x64'
          - name: Windows 32-bit
            os: windows-latest
            python-version: 3.9
            architecture: 'x86'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Qt dependencies
        if: startsWith(matrix.os, 'ubuntu')
        uses: tlambert03/setup-qt-libs@v1

      - run: pip install PyQt5 PySide2
      - run: pip install PyQt6 PySide6
        if: ${{ matrix.architecture != 'x86'}}

      # In order for Qt to run without a screen, create a virtual one.
      - run: sudo apt-get install -y xvfb
        if: startsWith(matrix.os, 'ubuntu')
      - run: |
          Xvfb ':42' -screen 0, 1280x720x24 & disown
          echo "DISPLAY=:42" >> $GITHUB_ENV
        if: startsWith(matrix.os, 'ubuntu')

      - run: bash ./setup-environment.sh
      - run: pip freeze

      - run: pytest
        timeout-minutes: 3
        env:
          QT_VARIANT: pyqt5

      - run: pytest
        if: ${{ matrix.architecture != 'x86'}}
        timeout-minutes: 3
        env:
          QT_VARIANT: pyqt6

      - run: pytest
        timeout-minutes: 3
        env:
          QT_VARIANT: pyside2

      - run: pytest
        timeout-minutes: 3
        if: ${{ matrix.architecture != 'x86'}}
        env:
          QT_VARIANT: pyside6

      - run: pip install pyinstaller
      - run: pyinstaller frozen-pytest.spec
        working-directory: tests/PyInstaller_
      - run: ./dist/frozen-pytest/frozen-pytest ../..
        working-directory: tests/PyInstaller_
